# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gJt-Mj36wTYmwjwbeC_VvZ02JoMHPwkP
"""

import numpy as np

# 1. Broadcasting

# a) Add a 1D array [1, 2, 3] to each row of a 2D array [[10, 20, 30], [40, 50, 60]].

arr1 = np.array([[10, 20, 30], [40, 50, 60]])
arr2 = np.array([1, 2, 3])
result1 = arr1 + arr2
print(result1)

# b) Multiply a 2D array `[[1, 2], [3, 4]]` by a 1D array `[10, 20]` column-wise

arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([10, 20])
result2 = arr3 * arr4[:, np.newaxis]
print(result2)

# 2. Indexing and Slicing (High Dimensional Arrays)

arr = np.arange(1, 25).reshape(2, 3, 4)

# a) Extract the second slice along axis 0

result3 = arr[1]
print(result3)

# b) Extract all rows and the last column for all slices

result4 = arr[:, :, -1]
print(result4)

# c) Reverse the order of slices along axis 0

result5 = arr[::-1]
print(result5)

# d) Set all even elements in the array to -1

arr[arr % 2 == 0] = -1
print(arr)

# 3. np.repeat

arr5 = np.array([1, 2, 3, 4, 5, 6])

# a) Every odd element repeated twice

result6 = np.repeat(arr5[arr5 % 2 == 1], 2)
print(result6)

# b) Elements repeated based on their value

result7 = np.repeat(arr5, arr5)
print(result7)

# 4. Normalizing

arr6 = np.array([10, 20, 30])
result8 = (arr6 - arr6.min()) / (arr6.max() - arr6.min())
print(result8)

# 5. Bonus Challenge

# a) Create a 3x3 matrix where each element at position (i, j) is i * j

result9 = np.fromfunction(lambda i, j: i * j, (3, 3), dtype=int)
print(result9)

# b) Replace all elements on the main diagonal of a 4x4 matrix with 0

matrix = np.random.randint(1, 10, (4, 4))
np.fill_diagonal(matrix, 0)
print(matrix)